server:
  port: 8080

logging:
  level:
    root: info

# actuator
management:
  server:
    port: 13520
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true

spring:
  banner:
    location: classpath:/banner.txt
  main:
    allow-bean-definition-overriding: true
